### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by pwang1997** [pwang1997/b2c-online-clothing-store#1]
- [x] Well-defined navigation bar with at least 5 relevant web pages
- [x] A search bar
- [x] External links (e.g., social media icons)
- [x] At least 2 internal links (e.g., featured contents with some images)
- - [x] promoted products
- - [x] seasonal products
- [x] A slideshow, video or any visual media (e.g., ads for products or services)
- [x] A call to action (CTA), e.g., create an account, book a demo, subscriber opt-in newsletter
- [x] Add 2 services (blog, payment, live chat, location, etc.)
-  -  [x] Google OAuth login
-  -  [x] Payment

**Comment by LydiaJiaruiLi** [comment]
Jiarui Li To Do: Payment and checkout

**Comment by pwang1997** [comment]
Zhengliang Wang: Search Bar, OAuth Login, NavBar

**Comment by Liuyi95** [comment]
product category/product gallery

**Comment by HaoJing-Leo** [comment]
Hao Jing: External links and internal links

**Comment by 1036240858** [comment]
Home page and product details page(slideshow etc.)
